# Generated by Django 4.2 on 2025-04-05 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_admin_access',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход в админку'),
        ),
    ]
